// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKUh1Sbd40v4A4WU78gjleIC9loO19GZI',
    appId: '1:824014394534:web:d4a457f3e6b24491511067',
    messagingSenderId: '824014394534',
    projectId: 'kigali-city-services-eed30',
    authDomain: 'kigali-city-services-eed30.firebaseapp.com',
    storageBucket: 'kigali-city-services-eed30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBPcXz-P8HRV64UO5kCuriWvGUENzjLHs',
    appId: '1:824014394534:android:c0ad6c9a3993975e511067',
    messagingSenderId: '824014394534',
    projectId: 'kigali-city-services-eed30',
    storageBucket: 'kigali-city-services-eed30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdIyeR_6M3wNWQqkeUf5cfMMVFP_OmPR0',
    appId: '1:824014394534:ios:a8d4b76d5a12c55b511067',
    messagingSenderId: '824014394534',
    projectId: 'kigali-city-services-eed30',
    storageBucket: 'kigali-city-services-eed30.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdIyeR_6M3wNWQqkeUf5cfMMVFP_OmPR0',
    appId: '1:824014394534:ios:a8d4b76d5a12c55b511067',
    messagingSenderId: '824014394534',
    projectId: 'kigali-city-services-eed30',
    storageBucket: 'kigali-city-services-eed30.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKUh1Sbd40v4A4WU78gjleIC9loO19GZI',
    appId: '1:824014394534:web:8c0dbabc4d99d970511067',
    messagingSenderId: '824014394534',
    projectId: 'kigali-city-services-eed30',
    authDomain: 'kigali-city-services-eed30.firebaseapp.com',
    storageBucket: 'kigali-city-services-eed30.firebasestorage.app',
  );
}
